[package]
name = "wgpu-triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# resolver="2"

[dependencies]
wgpu = "0.12.0"
winit = "0.26"
env_logger = "0.8"
pollster = "0.2"